version: "3.7"

services:
    debug: &debug
      image: paw:latest
      env_file:
        - .env
      build:
        context: .
        dockerfile: app/Dockerfile
        args:
          - "--include=*.txt"
          - "--include=*.jpg"
      runtime: nvidia
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                device_ids: ["0"]
                capabilities: [gpu]
      volumes:
        - ./:/opt/dev/
        - /usr/local/cuda:/usr/local/cuda
        - ${DATASET_DIR}:/data/
        - ${WEIGHTS}:/weights/
        - ${OUTPUT_DIR}:/output/
      stdin_open: True

    jupyter:
      << : *debug
      container_name: paw_jupyter
      ports:
        - "8000:8000"
      environment:
        - JUPYTER_TOKEN=rafa
      entrypoint: ["jupyter-lab", "--ip", "0.0.0.0", "--port", "8000", "--allow-root"]

    data2pipeline:
      << : *debug
      container_name: paw_data2pipeline
      command:
        bash -c "
        pip install -e . && \
        python -m app.run.data2pipeline --config ./app/config/train.yaml --singles
        "

    training:
      << : *debug
      container_name: paw_training
      command:
        bash -c "
        pip install -e . && \
        python -m app.run.train --config ./app/config/train.yaml --epochs 512 --device 0 --batch 64
        "

    paw_web:
      container_name: paw_webui
      image: webui:latest
      build:
        context: .
        dockerfile: webui/Dockerfile
      ports:
        - "5000:5000"
      volumes:
        - ${OUTPUTDIR}:/results/
        - ${DATADIR}:/uploads/
      stdin_open: True
#      entrypoint: ["python", "app.py"]

    paw_api:
      container_name: paw_api
      image: paw_api:latest
      build:
        context: .
        dockerfile: api/Dockerfile
      ports:
        - "7000:7000"
      volumes:
        - ${OUTPUTDIR}:/results/
        - ${DATADIR}:/uploads/
        - ${WEIGHTS}:/weights/
      stdin_open: True
#      entrypoint: ["python", "app.py"]
